apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: awx-operator-0.26.0-60-gfd44676
  name: awx-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
